import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/src/context/AuthContext";
import "semantic-ui-css/semantic.min.css";
import "@/src/scss/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>asdad</p>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
